# Generated by Django 5.0.3 on 2024-04-04 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_kitchen', '0002_alter_cook_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, error_messages={'max_decimal_places': 'Price must have at most 2 decimal places.', 'max_digits': 'Price must have no more than 5 digits in total.'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
